name: "Lean update"
description: "Attempts to update lean and dependencies of a lean project"
author: "Oliver Butterley"
inputs:
  on_update_succeeds:
    description: |
      What to do when an update is available and the build is successful.
      Allowed values: "silent", "commit", "issue" or "pr".
      Default: "silent".
    required: true
    default: "silent"
  on_update_fails:
    description: |
      What to do when an update is available and the build fails.
      Allowed values: "silent", "issue" or "pr".
      Default: "silent".
    required: true
    default: "silent"
  what_to_update:
    description: |
      Specifies which files, when updated by executing `lake update`, are considered as updated.
      Allowed values: "lean-toolchain" or "lake-manifest.json".
      Default: "lean-toolchain"
    required: false
    default: "lean-toolchain"
  token:
    description: |
      A Github token to be used for committing
    required: true
    default: ${{ github.token }}
outputs:
  result:
    description: "The action outputs `up-to-date`, `update-succeeds` or `update-fails` depending on the three possible scenarios."
    value: ${{ steps.record-outcome.outputs.outcome }}
runs:
  using: "composite"
  steps:
    # Running `lake update` also updates lean-toolchain, so this is not needed
    # - name: Update lean-toolchain
    #   run: ${{ github.action_path }}/scripts/getLatest.ps1
    #   env:
    #     GH_TOKEN: ${{ github.token }}
    #   shell: pwsh

    - name: Install elan
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
      shell: bash

    - name: Update dependencies of ${{ github.repository }}
      run: lake -R -Kenv=dev update
      shell: bash

    - name: Check if lean-toolchain or lake-manifest.json were updated
      id: check-update
      run: |
        Write-Host "info: Checking for changes of $env:WHAT_TO_UPDATE"
        $result = & "${{ github.action_path }}/scripts/checkChanges.ps1" | ConvertFrom-Json
        echo "files_changed=$($result.files_changed)" >> "$env:GITHUB_OUTPUT"
        echo "changed_files=$($result.changed_files)" >> "$env:GITHUB_OUTPUT"
        Write-Host "info: $( $result | Out-String)"
      env:
        WHAT_TO_UPDATE: ${{ inputs.what_to_update }}
      shell: pwsh

    - name: Try to build lean if something was updated
      if: steps.check-update.outputs.files_changed == 'true'
      id: build-lean
      continue-on-error: true
      uses: leanprover/lean-action@v1
      with:
        build-args: "--log-level=warning"

    - name: Record outcome
      id: record-outcome
      run: |
        if ("${{steps.check-update.outputs.files_changed}}" -eq "false") {
          Write-Host "No update available"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "outcome=no-update"
          exit 0
        } elseif ("${{steps.build-lean.outcome}}" -eq "success") {
          Write-Host "Update available and build successful"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "outcome=update-success"
        } elseif ("${{steps.build-lean.outcome}}" -eq "failure") {
          Write-Host "Update available but build fails"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "outcome=update-fail"
        }
      shell: pwsh

    # ------------------------- #
    # when update is successful #
    # ------------------------- #
    - name: Open PR if the updated lean build was successful
      if: steps.build-lean.outcome == 'success' && inputs.on_update_succeeds == 'pr'
      uses: peter-evans/create-pull-request@v7
      with:
        title: "Updates available and ready to merge"
        body: ""
        delete-branch: true
        branch-suffix: random
        branch: auto-update/patch
        labels: "auto-update-lean"

    - name: Open issue if the updated lean build was successful
      if: steps.build-lean.outcome == 'success' && inputs.on_update_succeeds == 'issue'
      run: |
        $files = "${{ steps.check-update.outputs.changed_files }}"
        $bullet_list = ""
        foreach ($file in $files -split ' ') {
          $bullet_list += "- $file`n"
        }
        $body = "Files changed in update:`n$bullet_list"
        gh issue create --title "$env:TITLE" --label "$env:LABELS" --body $body
      env:
        # Could be best to use the default token here
        GH_TOKEN: ${{ inputs.token }}
        GH_REPO: ${{ github.repository }}
        TITLE: Updates available and have been tested to build correctly
        LABELS: "auto-update-lean"
      shell: pwsh

    - name: Commit update if the updated lean build was successful
      if: steps.build-lean.outcome == 'success' && inputs.on_update_succeeds == 'commit'
      uses: EndBug/add-and-commit@v9.1.4
      with:
        default_author: github_actions
  
    # ----------------- #
    # when update fails #
    # ----------------- #
    - name: Open issue if the updated lean build fails
      if: steps.build-lean.outcome == 'failure' && inputs.on_update_fails == 'issue'
      run: |
        $files = "${{ steps.check-update.outputs.changed_files }}"
        $bullet_list = ""
        foreach ($file in $files -split ' ') {
          $bullet_list += "- $file`n"
        }
        $body = "Try `lake update` and then investigate why this update causes the lean build to fail.`nFiles changed in update:`n$bullet_list"
        gh issue create --title "$env:TITLE" --label "$env:LABELS" --body $body
      env:
        GH_TOKEN: ${{ inputs.token }}
        GH_REPO: ${{ github.repository }}
        TITLE: "Updates available but manual intervention required"
        LABELS: "bug"
      shell: pwsh

    - name: Action fails if the updated lean build fails
      if: steps.build-lean.outcome == 'failure' && inputs.on_update_fails == 'fail'
      run: exit 1
      shell: bash

branding:
  icon: "download-cloud"
  color: "blue"
