name: Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  plain_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Lean package
        id: update
        uses: Seasawher/lean-update@develop
        with:
          on_update_succeeds: "silent"
          lake-package-directory: "./test/Foo"

      - name: This update should succeed
        if: steps.update.outputs.result != 'update-success'
        run: exit 1

  fail_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Lean package
        id: update
        uses: Seasawher/lean-update@develop
        with:
          on_update_fails: "silent"
          lake-package-directory: "./test/Fail"

      - name: This update should fail
        if: steps.update.outputs.result != 'update-fail'
        run: exit 1